import { CAGE, ENC, ENC_MOUNT, PV_BRACKET, F_ABOVE, F_BELOW, GROUT_T, GUSSET_T, INCH } from './config.js';

export const PARTS = {
  pole: { name: 'Tiang Monopole', group: 'Struktur', specs: d => [
    ['Material', 'Pipa baja, cat biru'],
    ['Diameter luar', `${d.od} mm (${INCH[d.od]} SCH40)`],
    ['Tebal dinding', `${d.wall} mm`],
    ['Tinggi', `${d.height.toFixed(2)} m dari base plate`],
    ['Berat pipa ±', `${d.kg.toFixed(0)} kg`],
  ]},
  cap: { name: 'Tutup Atas (Pole Cap)', group: 'Struktur', specs: d => [
    ['Fungsi', 'Penutup ujung pipa, cegah air hujan masuk'],
    ['Diameter', `${(d.od + 6).toFixed(0)} mm`],
  ]},
  solarPanel: { name: 'Panel Surya', group: 'Panel Surya', specs: d => [
    ['Ukuran (perkiraan)', `${d.pvW} × ${d.pvD} × 35 mm`],
    ['Kemiringan (perkiraan)', `${d.pvTilt}°`],
    ['Arah hadap', 'Searah krangkeng / muka box'],
    ['Posisi', 'Ujung atas tiang'],
  ]},
  solarBracket: { name: 'Bracket Panel Surya', group: 'Panel Surya', specs: d => [
    ['Material', `Plat aluminium ${PV_BRACKET.t} mm ditekuk (kanal U)`],
    ['Lebar', `${PV_BRACKET.W} mm`],
    ['Plat belakang', `${PV_BRACKET.W} × ${d.pvBrH} mm, 4 lubang U-bolt`],
    ['Sayap', `2 sayap segitiga, panjang = kedalaman panel (${d.pvD} mm), ujung lancip`],
    ['Ke panel', '4 baut di bibir sayap, tepat di rangka depan & belakang panel'],
    ['Klem ke tiang', '2 × U-bolt M10'],
  ]},
  sp21: { name: 'Konektor SP21 2 Pin', group: 'Panel Surya', specs: d => [
    ['Tipe', 'Weipu SP21, 2 pin, IP68 (ulir)'],
    ['Posisi', 'Dinding bawah box, kanan (dilihat dari depan)'],
    ['Fungsi', 'Masukan kabel panel surya → MPPT'],
    ['Lubang panel', 'Ø21 mm'],
    ['Soket', 'Mur belakang (perkiraan), 2 kabel masuk duct kanan'],
    ['Plug', 'Mur kopling Ø29 × 60 mm (perkiraan)'],
  ]},
  pvCable: { name: 'Kabel Panel Surya + Conduit', group: 'Panel Surya', specs: d => [
    ['Kabel', '2 inti, Ø9 mm (perkiraan)'],
    ['Pelindung', 'Conduit fleksibel bergelombang hitam Ø16 mm (perkiraan)'],
    ['Jalur', 'SP21 → lubang mesh bawah krangkeng → naik di sisi belakang-kanan tiang → junction box panel'],
  ]},
  antiClimb: { name: 'Antipanjat', group: 'Struktur', specs: d => [
    ['Jari-jari', '8 batang besi Ø12 mm, satu garis (sebidang)'],
    ['Bentuk', 'Keluar ± 0.27 m, ujung ditekuk ke bawah ± 0.16 m (perkiraan)'],
    ['Pemasangan', 'Kerah klem di tiang'],
    ['Tinggi', `${d.acY.toFixed(2)} m dari tanah`],
  ]},
  gusset: { name: 'Stiffener / Gusset', group: 'Struktur', specs: d => [
    ['Jumlah', '4 pcs, jarak 90°'],
    ['Tebal', `${GUSSET_T} mm`],
    ['Tinggi × lebar', `${d.gh} × ${Math.round(d.gw)} mm`],
    ['Sambungan', 'Las ke tiang & base plate'],
  ]},
  plate: { name: 'Base Plate', group: 'Sambungan', specs: d => [
    ['Dimensi', `${d.plate} × ${d.plate} × ${d.plateT} mm`],
    ['Lubang angkur', `4 × Ø${d.bolt + 2} mm`],
    ['Pola lubang', `${d.s} × ${d.s} mm (persegi)`],
    ['Lubang kabel', `Ø${d.cableHole} mm di tengah`],
    ['Sambungan', 'Las keliling ke tiang'],
  ]},
  anchor: { name: 'Baut Angkur', group: 'Sambungan', specs: d => [
    ['Ukuran', `M${d.bolt}`],
    ['Tipe', 'L-bolt (J-bolt), baja ST-41 galvanis'],
    ['Jumlah', '4 titik'],
    ['Panjang total ±', `${d.boltLen} mm`],
    ['Tertanam di beton', `${d.nut.emb} mm`],
    ['Tonjolan di atas beton', `${d.proj} mm`],
  ]},
  nut: { name: 'Mur & Ring Atas', group: 'Sambungan', specs: d => [
    ['Susunan', 'Ring plat + mur + mur kontra (double nut)'],
    ['Ukuran mur', `M${d.bolt}, kunci ${d.nut.af} mm`],
    ['Jumlah', '4 set'],
  ]},
  levelNut: { name: 'Mur Perata (Leveling)', group: 'Sambungan', specs: d => [
    ['Fungsi', 'Menyetel ketinggian & vertikalitas tiang'],
    ['Ukuran mur', `M${d.bolt} + ring plat`],
    ['Posisi', 'Di bawah base plate, dalam lapisan grouting'],
  ]},
  grout: { name: 'Grouting', group: 'Pondasi', specs: d => [
    ['Material', 'Non-shrink grout'],
    ['Tebal', `${GROUT_T} mm`],
    ['Fungsi', 'Mengisi celah base plate – beton'],
  ]},
  foundation: { name: 'Pondasi Beton', group: 'Pondasi', specs: d => [
    ['Material', "Beton bertulang K-250 (fc' 20 MPa)"],
    ['Dimensi', `${d.fw} × ${d.fw} × ${F_ABOVE + F_BELOW} mm`],
    ['Di atas tanah', `${F_ABOVE} mm`],
    ['Tertanam', `${F_BELOW} mm`],
  ]},
  enclosure: { name: 'Enclosure B&J 504020', group: 'Enclosure', specs: d => [
    ['Dimensi (L×T×D)', `${ENC.W} × ${ENC.H} × ${ENC.D} mm`],
    ['Orientasi', 'Portrait (gambar pabrik 510 × 410 diputar 90°)'],
    ['Kedalaman base', `${ENC.joint} mm + tutup ${ENC.D - ENC.joint} mm`],
    ['Lebar dengan flange', `${ENC.W + 2 * ENC.flange} × ${ENC.H + 2 * ENC.flange} mm`],
    ['Tinggi pasang', `${d.encY.toFixed(2)} m (tengah box dari tanah)`],
  ]},
  door: { name: 'Tutup / Pintu', group: 'Enclosure', specs: d => [
    ['Bukaan', 'Ke kanan (engsel di sisi kanan)'],
    ['Kedalaman tutup', `${ENC.D - ENC.joint} mm, dinding ${ENC.t} mm`],
    ['Muka', 'Panel timbul di tengah'],
    ['Seal', 'Gasket karet keliling'],
  ]},
  hinge: { name: 'Engsel', group: 'Enclosure', specs: d => [
    ['Jumlah', '3 pcs, sisi kanan'],
    ['Posisi', 'Tengah + ±185 mm dari tengah'],
    ['Tipe', '3 knuckle dengan pin'],
  ]},
  latch: { name: 'Latch / Kunci Klip', group: 'Enclosure', specs: d => [
    ['Jumlah', '3 pcs, sisi kiri'],
    ['Posisi', 'Tengah + ±185 mm dari tengah'],
    ['Tab buka', `Tab "OPEN" ${ENC.openTabY} mm di atas tengah`],
  ]},
  logger: { name: 'Beacon Logger', group: 'Isi Enclosure', specs: d => [
    ['Tipe', 'Beacon Logger BE-BL110 (V2)'],
    ['Dimensi', '120 × 120 × 37 mm (dengan flange)'],
    ['Terminal kiri', '24V · 12V · 5V · Tx1 · Rx1 · A · B · S1 · G · RST'],
    ['Terminal bawah', 'A1 · G · A3 · G · D1 · G · D2 · R1 · + · −, ETH, USB'],
    ['Muka', 'LCD, USB-A, SD card, Type-C, Port I/O (DB9)'],
    ['Samping kanan', 'SMA antena GPS'],
    ['Posisi', 'Kiri atas'],
  ]},
  dataSender: { name: 'Data Sender', group: 'Isi Enclosure', specs: d => [
    ['Fungsi', 'Pengirim data (router / modem seluler)'],
    ['Dimensi', '155 × 95 × 25 mm (P × L × T)'],
    ['Port', '3 × SMA antena, DC power, reset, Console, LAN, WAN/LAN'],
    ['Indikator', 'WAN/LAN, LAN, System, WIFI, Online, SIM, sinyal, Power'],
    ['Slot', 'SIM / UIM'],
    ['Pemasangan', 'Rebah di bracket siku kanan atas, ventilasi menghadap pintu'],
  ]},
  antenna: { name: 'Antena', group: 'Isi Enclosure', specs: d => [
    ['Antena magnet', '2 pcs, whip dengan pegas, menggantung di bawah data sender'],
    ['Antena stik', '1 pcs, vertikal di sisi kanan'],
  ]},
  mppt: { name: 'Solar Charge Controller (MPPT)', group: 'Isi Enclosure', specs: d => [
    ['Tipe', 'BSC-20 Solar MPPT — MPPT T20A'],
    ['Dimensi', '140 × 85 × 45 mm (L × T × tebal)'],
    ['Sistem', '12 V / 24 V, 20 A'],
    ['Maks. PV', '260 W @ 12 V · 520 W @ 24 V'],
    ['Voc panel maks', '≤ 24 V (12 V) · ≤ 48 V (24 V)'],
    ['Terminal', '6: panel surya, baterai, beban (+/−)'],
    ['Lain-lain', 'Port sensor suhu di sisi samping'],
  ]},
  cableDuct: { name: 'Kabel Duct', group: 'Isi Enclosure', specs: d => [
    ['Tipe', 'Slotted wiring duct, abu-abu'],
    ['Jalur', 'Horizontal melintang di tengah + vertikal di kanan + pendek di bawah fuse'],
    ['Ukuran ±', '25–30 × 40 mm (perkiraan)'],
  ]},
  wagoFuse: { name: 'WAGO Fuse', group: 'Isi Enclosure', specs: d => [
    ['Tipe', 'Terminal fuse DIN rail + end plate oranye'],
    ['Jumlah ±', '8 modul'],
    ['Rel', 'DIN 35 mm'],
  ]},
  terminal: { name: 'Terminal Block', group: 'Isi Enclosure', specs: d => [
    ['Tipe', 'Terminal barrier sekrup'],
    ['Jumlah', '2 baris'],
    ['Posisi', 'Kanan bawah, di bawah kabel duct pendek'],
  ]},
  battery: { name: 'Baterai', group: 'Isi Enclosure', specs: d => [
    ['Dimensi', '230 × 185 × 140 mm (P × T × L)'],
    ['Tipe', 'Aki VRLA 12 V'],
    ['Posisi', 'Kiri bawah, di lantai box'],
  ]},
  mountPlate: { name: 'Mounting Plate', group: 'Enclosure', specs: d => [
    ['Dimensi', `${ENC.mp.w} × ${ENC.mp.h} × ${ENC.mp.t} mm (portrait)`],
    ['Tipe', 'Perforated (berlubang kotak)'],
    ['Lubang pasang', `4 × Φ5, pola ${ENC.mp.slotX} × ${ENC.mp.slotY} mm`],
    ['Ruang bebas ke tutup', '± 122 mm (sampai sambungan)'],
  ]},
  encMount: { name: 'Dudukan Enclosure', group: 'Krangkeng', specs: d => [
    ['Besi strip', `2 × flat bar ${ENC_MOUNT.stripW} × ${ENC_MOUNT.stripT} mm, dilas melintang di rangka belakang krangkeng`],
    ['Posisi', 'Di belakang tepi atas & bawah enclosure'],
    ['Baut', `4 × M${ENC_MOUNT.bolt} dari belakang strip, masuk ke mur tanam box`],
    ['Mur tanam', 'Di keempat sudut punggung enclosure'],
  ]},
  bracket: { name: 'Klem Tiang Krangkeng', group: 'Krangkeng', specs: d => [
    ['Tipe', 'Klem 2 bagian, plat 5 mm, cat biru'],
    ['Bagian depan', 'Setengah lingkar dilas ke rangka belakang krangkeng'],
    ['Bagian belakang', 'Strap setengah lingkar, lepas-pasang'],
    ['Jumlah', '2 set — rangka belakang atas & bawah'],
    ['Baut', '2 × M10 per klem, lewat kuping kiri & kanan'],
    ['Untuk pipa', `${INCH[d.od]} (OD ${d.od} mm)`],
  ]},
  cage: { name: 'Krangkeng Pelindung', group: 'Krangkeng', specs: d => [
    ['Dimensi (L×T×D)', `${CAGE.W} × ${CAGE.H} × ${CAGE.D} mm (standar)`],
    ['Pembagian', `Badan ${CAGE.split} mm + pintu ${CAGE.D - CAGE.split} mm`],
    ['Rangka', `Besi hollow ${CAGE.tube} × ${CAGE.tube} mm`],
    ['Jaring', `Wiremesh Ø${CAGE.wire} mm, kotak ${CAGE.mesh} × ${CAGE.mesh} mm`],
    ['Warna', 'Cat biru'],
  ]},
  cageDoor: { name: 'Pintu Krangkeng', group: 'Krangkeng', specs: d => [
    ['Bentuk', `Baki: muka depan + ${(CAGE.D - CAGE.split) / 10} cm sisi kiri, kanan, atas & bawah`],
    ['Engsel', `3 pcs di sisi kanan, pada garis ${CAGE.split / 10} cm`],
    ['Kunci', `Gembok di sisi kiri, pada garis ${CAGE.split / 10} cm`],
    ['Rangka', `Hollow ${CAGE.doorTube} × ${CAGE.doorTube} mm + wiremesh`],
  ]},
  padlock: { name: 'Kotak Gembok', group: 'Krangkeng', specs: d => [
    ['Kotak', `Plat 4 sisi (70 × 120 × 85 mm), dilas di sisi kiri badan pada garis ${CAGE.split / 10} cm`],
    ['Celah', 'Celah horizontal di muka depan kotak, pas untuk lidah pintu'],
    ['Staple', 'Plat datar berlubang dilas ke tiang, di dalam kotak'],
    ['Gembok', 'Masuk dari bawah, lewat lubang staple, lidah pintu & lidah penutup'],
  ]},
  hasp: { name: 'Lidah Kunci Pintu', group: 'Krangkeng', specs: d => [
    ['Bentuk', 'Plat datar berlubang, sudut dipotong'],
    ['Posisi', 'Dilas di rangka belakang-kiri pintu (garis bagi)'],
    ['Fungsi', 'Masuk lewat celah kotak, menumpuk di atas staple'],
  ]},
  lockLid: { name: 'Penutup Atas Kotak Gembok', group: 'Krangkeng', specs: d => [
    ['Bentuk', 'Plat penutup + flange pengarah + lidah berlubang'],
    ['Pengunci', 'Lidah penutup ikut dikunci gembok, tidak bisa diangkat'],
    ['Saat dibuka', 'Gembok dilepas → penutup diangkat lepas → pintu bisa dibuka'],
  ]},
  conduit: { name: 'Conduit Kabel', group: 'Pondasi', specs: d => [
    ['Material', `Pipa PVC Ø${Math.round(d.conduitR * 2)} mm`],
    ['Fungsi', 'Jalur kabel sensor / daya ke dalam tiang'],
    ['Jalur', 'Naik ke lubang kabel base plate, keluar samping pondasi'],
  ]},
};
